### ISSUE TITLE
After recording if user play immediately audio not working

### ISSUE THREAD

**Issue by sunny131984** [AshvinGudaliya/AudioRecorder#1]
* Its really cool and neat code.
* I am facing issues when I try to make toggle on record and play at that time its playing is failed.
* It gives below error for audio tatus.

Error : 
-[AVAudioSession setActive:withOptions:error:]
: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.

**Comment by mitulmarsonia** [comment]
I have same issue
